dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=terraform-sage

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Windows
    - env: TARGET=x86_64-pc-windows-gnu

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:

  api_key:
    secure: Qp55mXf6lv1mSVXhiTBIbWZGdDD9yYQlyNU7j0ElfuY+IDcvA9XZSDmYy5prQ2LTlZZGSG4+iYU8Gvg9MkiuAlQfP0opSF3sV+UQTBtncv7oUJwBkOspM4YfAMlHBqkv94rNqVjmsg6+QP+N3uKqfQSOX9r3re7wCk9paczMQCyR36assB/WDjcsU+3+Rx8bciD7+wv3wJjxqdxP4S07UdPhKtjDKN1A6GrkzPCkPLU05AYR5zeaGENdmni1NlP+TPfv41M0EJatNcb731RnFuBgS5KhcjlN8C8miy149qEBeJpGBi2qzxNpWZ4vhq4fRKXA3ms1goL73h4z6OoE+FAqhUnKXNfX4LqFvd8dWfllPCnjbzFI3BRz9kAxhbtIER88p6sIf5jT/RWoeyT0ShqZrnUXA72ubweCnEH/Tj39PoR3ZMh1CyDoqTf/SKszUHSzymuhbbmebHTHw97HPhgx8o2hzvEfYEPXwzRWFlpZL0gjB9Llh0fg1jS1U3EBj3V5Wl9FVb5fLcHvTzUyaCV8lUSHRMjdXCbiW2wyBOcf9weexTfZ60hIYFbo/n75bcU7vD884u0WofxDQXt0Of0enw0fG597Fmdv9q551vFUJZjDnv+jjtwgTpl3seKWf7XOOEd0Qy1fLI+4LbPIuuRLI0mje159uJlcx1SjVjk=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
