[package]
name = "terraform-sage"
version = "0.1.0"
authors = ["Valeryi Savich <relrin78@gmail.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.12"
clap = "2.31"
structopt = "0.2.18"
structopt-derive = "0.2.18"
quick-error = "1.2.2"